### ISSUE TITLE
SetKey(s) retains custom grid

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#209] opened 2016-12-01 01:27 UTC
When using `SetKey(s)` consecutively with `clear` set to `true`, the custom grid is not reset.

The fix is already implemented and in the develop branch.

**Comment by Sharparam** [comment] 2016-12-01 20:32
Is this not a duplicate of #198?

**Comment by Sharparam** [comment] 2016-12-09 23:03
Closing as duplicate of #198.

**Closed by Sharparam** 2016-12-09 23:03 UTC
Labels: Bug, Ready
