### ISSUE TITLE
Update Clear to use Effect.None instead

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#163] opened 2016-06-06 09:23 UTC
On some devices, using `.Clear()` doesn't work (and has never worked) as expected, in that it should be instantaneous. I don't think using `SetAll(Color.Black);` to clear the LEDs is advantageous over using the provided `None` effect, especially since on some devices such as the headset, the clear function is not instant.

**Comment by brandonscott** [comment] 2016-06-06 09:25
On the Blade it throws an exception that it's gone over the max columns.

**Comment by Sharparam** [comment] 2016-06-06 09:28
Re: Blade: That means anything setting the entire grid will bug out and needs to be looked into as well.

**Comment by brandonscott** [comment] 2016-06-06 21:09
@njbmartin Did you mean the Blade?  If so, the latest developments for #143 fixes this.  I believe the thinking behind using `SetAll(Color.Black)` is that this was more instant when @Sharparam and I were testing in the early days compared to the `None` effect.

Any other devices this doesn't work on @njbmartin ?  Is the delay in both implementations on Headset noticeable?  We could specifically implement `None` on Headset.

**Comment by njbmartin** [comment] 2016-06-06 21:22
Yes, speaking about the headset again. Sorry chaps, but to mean Effect.None makes more sense to use as opposed to setting all to black.

It takes a good second or two to fade to black. Having Clear overridden on Headset to use None is exactly how I was using it.

**Comment by Sharparam** [comment] 2016-06-06 21:30
The delay is what made us implement `Clear` using the set to black method instead. Since setting a color is instant it is preferable for the `Clear` method.

**Comment by brandonscott** [comment] 2016-06-06 21:45
Indeed.  I just tried setting the Headset to Black manually but its just a less bright version of the previous color whether that be from Colore or Synapse.  Is this expected @njbmartin ?  No other device has this issue.

**Comment by brandonscott** [comment] 2016-06-15 13:52
Any further thoughts on this?

**Comment by Sharparam** [comment] 2016-06-15 15:56
Does this bring any performance enhancements on the headset by switching to using `None`? We can't switch to `None` for devices that support custom effects since that will introduce the fading delay instead of an instant clear effect.

Could we inquire Razer as to why exactly there is a delay when switching between pre-defined effects? Inside Synapse it makes sense because it gives a user-friendly effect I guess, but when developing apps it makes no sense.

**Comment by Sharparam** [comment] 2016-06-15 16:01
Has this changed recently then? When we first implemented `Clear`, using `None` had a delay before the effect was actually cleared.

**Comment by njbmartin** [comment] 2016-06-15 16:03
On the headset at least, using `None` has never had a noticeable delay. Considering using SetAll() on a headset causes a 2 second delay, it's advisable considering you'd expect clear to be instant.

**Comment by Sharparam** [comment] 2016-06-15 16:04
How is this on other devices when using `None`?

**Comment by njbmartin** [comment] 2016-06-15 16:06
Only one way to find out. Testing with a few now.

**Comment by njbmartin** [comment] 2016-06-15 16:31
Please see the above feature branch. Tested on BW TE, Kraken, Mamba TE and diamond back

**Comment by Sharparam** [comment] 2016-06-15 16:31
So it's confirmed that using `None` is now instant for all devices.

**Comment by njbmartin** [comment] 2016-06-15 16:35
If you could try it out and let me know your thoughts, it's instant enough for me.

**Comment by Sharparam** [comment] 2016-06-15 16:36
I only have my laptop which is running Arch at the moment so I'm unable to test. @brandonscott?

**Comment by brandonscott** [comment] 2016-06-15 17:03
As @njbmartin said, it's now completely instant, no fading.  When on Earth did this happen?  We need full changelogs!

**Comment by njbmartin** [comment] 2016-06-15 17:13
Interesting note. When using SetAll, it might be worth using Clear first. On the headset at least, SetAll is not instant unless clear has been used first.

**Comment by Sharparam** [comment] 2016-06-15 17:15
Headset has no Custom effect, so `SetAll` uses static, which has a fade delay like most pre-defined effects.

**Comment by njbmartin** [comment] 2016-06-15 17:29
You are right in that it has no custom effect and that SetAll does indeed fade, but SetAll changes instantly if Clear is used prior.

**Comment by Sharparam** [comment] 2016-06-15 17:38
Seems like odd behaviour, we should ask Razer why the SDK has these inconsistencies.

**Comment by njbmartin** [comment] 2016-06-15 17:39
Something to do with the driver itself for the headset. As mentioned before, it's not something they're going to fix.

**Comment by Sharparam** [comment] 2016-06-15 17:42
They're not going to fix bugs in the SDK?

**Comment by njbmartin** [comment] 2016-06-15 17:43
It's not the SDK, its the Headset's driver.

**Comment by Sharparam** [comment] 2016-06-15 17:46
So your change is relying on a bug in the driver to work.

**Comment by njbmartin** [comment] 2016-06-15 17:47
TBH, that's just the answer Razer gave me back when i first raised this issue last year. Can't fix, won't fix was their response.

**Comment by Sharparam** [comment] 2016-06-15 18:01
Why did they release Chroma headsets if they have no intention of supporting them... What other inconsistencies like this are there?

**Comment by njbmartin** [comment] 2016-06-15 18:30
Just this one, dont forget this was a very early product.

**Comment by Xinhuan** [comment] 2016-06-15 20:07
> Interesting note. When using SetAll, it might be worth using Clear first. On the headset at least, SetAll is not instant unless clear has been used first.

> You are right in that it has no custom effect and that SetAll does indeed fade, but SetAll changes instantly if Clear is used prior. 

In my testing on a Kraken, using this method to cause a "instant color switch" (that is, by setting to Effect.None, then to the new color) will cause a noticeable flicker. The flicker is a result of the headset displaying "1 frame" of no lighting before displaying the new color,  It is particularly obvious when the headset is placed beside the Firefly/Keyboard/Mouse which exhibit no such flicker since they do not need to be set to an intermediate Effect.None.

Mark said that this is due to a limitation in the Headset firmware, and they are looking to address this in future products.

Due to the flicker, I would not recommend adding a Clear() call inside the SetAll() for Headset, unless there is an overload or additional parameter that makes the Clear() optional. That way, it is up to the developer to choose whether they want a flicker, or a "2 second fade to new color" when using SetAll().

**Comment by njbmartin** [comment] 2016-06-15 20:34
You're right, there is a noticeable flicker. Thanks for pointing that out.

However, SetAll on the Headset simply calls `SetStatic`, so if we leave SetStatic as is, then developers have a choice of fading slowly or "almost" instantly.

The "almost" instantly is a limitation at the firmware level, but the best we can provide to developers.

**Comment by brandonscott** [comment] 2016-06-15 20:44
I'd rather not go with the `Clear()` inside `SetAll()` now knowing there's a flicker.  At least by not clearing immediately there is a graceful effect rather than a flicker that isn't a good user experience.

I know neither option is what we want, but until the firmware is fixed, I'd stick without it for now.

**Comment by Sharparam** [comment] 2016-06-15 20:46
I'm inclined to agree with @brandonscott. Not having a call to `Clear` inside `SetAll` feels like the cleaner option with the other one being like a bandaid fix to something that really ought to be fixed in the firmware.

**Comment by njbmartin** [comment] 2016-06-15 20:50
Yep, happy with that. At least now with `Clear` using `Effect.None` devs can decide for themselves. 

Should we add extra comments to headset functions to make it clear that due to hardware limitations it does not work as expected?

**Comment by brandonscott** [comment] 2016-06-15 20:52
I quite like that idea to add a comment.  @Sharparam and I have done a similar thing to `Init()` in the past.

**Comment by Sharparam** [comment] 2016-06-15 21:00
@njbmartin Add it in a `<remarks>` section (or was it singular? I forgot, check other doc places).

**Comment by Sharparam** [comment] 2016-06-27 15:40
Implemented in #179

**Closed by Sharparam** 2016-06-27 15:40 UTC
Labels: In progress
